<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Sauce Demo</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>d936fb3c-bbbb-4d45-a380-ac29c1d299a6</testSuiteGuid>
   <testCaseLink>
      <guid>ca43a77a-d35d-4c3d-b9d8-2b6eb6699ea4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Skenario/Alfian/N1_Login Without User</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f1d52d5-ebee-4fb4-a64b-3366c3391765</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44be826b-bfba-4cef-81a3-ea72d78e2f73</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>19564030-d402-4d75-ad75-129300785882</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Skenario/N2_Login Without Password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff664a98-1a50-4ee8-a384-125372b8bfd5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd41e638-b30c-4408-a256-753fcace8033</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2aa5c781-b357-4f8a-96a7-143e3b520d1a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Skenario/N3_Login User and Pass Invalid</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>463ff0d7-32cd-4b92-9fe9-4a151098403b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aaddd57b-c16d-449e-bac9-07b3ac06d553</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>10e44f07-e645-48e3-b248-baa60f8465ef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Skenario/P1_Login Succes</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>abc1129a-ce93-4f1c-8493-1ed991b8b92e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fe76f908-0559-49c2-b5d0-11997a13a088</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bf8cc91b-01e7-4b91-a185-b24b27a7480e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Skenario/Alfian/P1_Name Z to A (Descending)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9817500c-b70d-419c-9634-e16b9e4d9bdb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>880c9d81-d599-4be5-9451-5d524395fed0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>65083903-6f04-4411-bd65-590767543ec2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>532a1b16-9a54-45a1-959f-14635a160eb0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Skenario/P2_Price Low to High</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0ca0e78-2f9a-440f-8feb-4a46e5af7731</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>861daac9-809a-48ec-9621-3abb09ae78fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2625052c-cc78-404d-a252-5a7c2b05cd26</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>80c1f6d5-b5d0-4910-ade8-15572f72f0a7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Skenario/P3_Filter High to Low</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf9521c6-e4b5-432c-a9c2-1537c7126dfa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b8b0cb35-83bf-425d-9825-bfadd3f8e2c9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b820d4e-daec-4ad7-8492-c4cf5d28fd51</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6b8acd90-d92a-4998-80da-330563d47d9d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Skenario/P4_FilterSearchAscending</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a46c45e7-57f9-42a1-a7bc-7292e66d157e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>577eeb8e-4d8c-4d26-8af9-c8785e71031f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>450cb204-429e-4569-8419-5b9695dd9616</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8761c86-c11c-4e3c-90d5-ce8a724409dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b2c4f77-966d-4b66-9d6e-92bd8a802e32</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>832a7aad-5e69-472c-9741-3819e31bd0b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5547009c-c1db-45f5-96ce-bae93d104c4b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>48732729-ca4e-463e-a272-a2fd763a5993</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Page/Cart/P1_Remove Cart</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e5423389-ddb0-48f9-9be7-d3a698f26e19</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>911f0d32-d829-429f-8683-8386c51d8207</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c1e8113a-9b6c-486a-adf0-e03cd9318c51</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Page/Cart/P2_Klik Back Countinue Shopping</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8630e364-61b5-463d-a6dd-8941b3146b52</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2540dc25-eda8-43fb-abe9-0f69b9d9e005</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e09c4e56-baad-4157-8765-7489866e5fac</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Skenario/P3_Add Cart Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ecc3f20-f835-4d20-b422-9283c2c075ba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ddc53704-e9aa-47de-9736-467f6e3797bf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>33d8b70d-3276-41a5-935e-6d624479e090</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Skenario/P4_CartAddMore</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d58b1372-565c-4fbd-985a-9fded90d9f7d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>20bf1c51-1812-4610-a493-9ce8fbb4b0cf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a517f87-08a2-4506-b69a-81774c1e767e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>359288c3-188b-48e6-ae88-bd399e3ee43f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28628d1f-47b7-4666-9a59-bb578a795f85</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6db29686-3814-4b6d-ab27-bfca234420d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>296cf6c6-620c-4fa0-9831-cae7332fdfaa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9c112170-673f-4f63-986e-c93f3889af7b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Skenario/Alfian/N1_Add With Out First Name</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff27dc03-4449-4ff8-8721-e143aeb80af8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c057bd51-0c0c-4014-a916-31dd14e21d6c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12d61712-e8d0-436b-825e-13f3ee28f320</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e354e440-3560-4dc5-a62c-ff2c7837af32</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86977d6b-b177-4dc2-b8f6-4491a1a2dc14</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f55c78cd-1df1-4168-a41d-e2a9ea7f9144</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Skenario/N2_Add Without Last Name</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e53d93e-8cc9-4840-b93a-85b3f86d9560</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>52cba478-3347-4e54-94b1-3afa1f2268a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5cd9bc7f-bbde-4e11-8e27-cc91d32b071f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8998a6d3-ade5-49b4-8bf0-74af691559a2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8af44a1-08a6-4a74-840b-188f59ae395d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1b3543d4-46b2-484e-822f-77f03262d32d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Skenario/N3_Add Without Postal Code</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b09a29bb-454e-43ca-bdb3-3c49a97aca59</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f4cbb68-b9e6-460f-a097-49b7af0ce4cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>708eea5e-8a9e-4b73-9ca8-49ab43f5402a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2900911b-fd54-4bed-95c2-e06ba5816760</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73e0ab4d-04ae-45f0-b212-31a1d4a796c7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2a6797bb-69cb-40b7-bef4-97fd77b08c7f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Skenario/N4_CheckoutBlankAll</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8fcd92a8-b4f4-4fd3-a054-9a6b9fb3d228</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4cd30d0-beb8-4e99-8434-7fff5758fe7f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f3d48329-5ed5-407d-839a-1cd0bf152353</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05e39347-dfbb-4caf-93a8-ace41ca64726</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>841cf01c-c7ae-4b2b-927f-07f19eaf8162</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57395bad-1353-4279-baf2-89b48df6e304</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88a6e13c-e61e-4f8b-8776-b1217822a34b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b9cff8ed-44dc-4263-a574-233f5675baec</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Skenario/Alfian/P1_Klick Cancel Checkout</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>29fe30f5-bb4b-444e-962e-4e7f7d0cd2dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4bc5b79-7d12-4752-8559-fdf69db3311c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35b56e94-ed78-4959-bf40-c5bbbc98f13a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46428a00-7c05-43e5-859d-3008a8feeaf8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5777d614-7ba2-4612-be59-7ebcc2350b6a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3453b2fd-738f-45dd-ae7a-dcc3c158d7e8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Skenario/P2_Success Checkout</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c2cd39f-6dd0-44a0-ae67-428d882aa491</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>357795b5-c1a5-4949-8659-c524c0905bc8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d2520df-cbec-4e32-baf9-962cb70cedd0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e868ebb-2ff2-4d75-a7b3-3d649cb67e94</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50237dee-310a-4482-929b-9e1c22677078</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a027674d-077c-4ef6-9544-495fd6edb001</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Page/Checkout/P3_Succes Checkout 2 or more Brand</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1437b85a-f4e5-4dc3-8cb5-83d9285b6c7c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51dd36f0-ac1d-47a7-baf0-313f787cfc55</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab77c2e3-d3f6-43fa-8283-9564a7ca9aa8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10392d95-3d22-4ba7-b424-0a1a0731d971</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5dcf7ff4-d44e-4604-aa8c-5f55f83795a1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>925772c4-80fe-4121-8bbe-51135478db64</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Page/Logout/P1_Succes Logout</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eefb3967-1c01-471e-b136-f9d6b183e293</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7359deb4-ef78-4cf3-84d4-2f22e99f5f96</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
