<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Select</description>
   <name>select</name>
   <tag></tag>
   <elementGuidId>4ac23419-d4c2-470b-80d8-321a6502946a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@class=&quot;product_sort_container&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
